bsp/nuclei: Fix when SOC changed to evalsoc build error
board/board.c:18:14: fatal error: drv uart.h: No such file or directory

Signed-off-by: Huaqi Fang <578567190@qq.com>